# Generated by Django 4.1 on 2022-10-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_app', '0003_tag_project_vote_ratio_project_vote_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='gettyimages-1208201572-594x594.jpg', null=True, upload_to=''),
        ),
    ]
