# Generated by Django 4.1.2 on 2022-10-24 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saas_app', '0007_project_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reform_name', models.CharField(max_length=2000)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
