# Generated by Django 4.0.7 on 2022-10-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_is_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_manager',
            new_name='manager',
        ),
    ]
